//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.2.11
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2016.06.26 at 08:39:15 AM EDT
//


package com.rsicms.rsuite.containerWizard.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;attribute name="content-permissions" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
 *       &lt;attribute name="project-role" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "ace")
public class Ace {

  @XmlAttribute(name = "content-permissions", required = true)
  @XmlSchemaType(name = "anySimpleType")
  protected String contentPermissions;
  @XmlAttribute(name = "project-role", required = true)
  protected String projectRole;

  /**
   * Gets the value of the contentPermissions property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getContentPermissions() {
    return contentPermissions;
  }

  /**
   * Sets the value of the contentPermissions property.
   * 
   * @param value allowed object is {@link String }
   * 
   */
  public void setContentPermissions(String value) {
    this.contentPermissions = value;
  }

  /**
   * Gets the value of the projectRole property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getProjectRole() {
    return projectRole;
  }

  /**
   * Sets the value of the projectRole property.
   * 
   * @param value allowed object is {@link String }
   * 
   */
  public void setProjectRole(String value) {
    this.projectRole = value;
  }

}
