//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.16 at 08:33:36 AM EDT 
//


package com.rsicms.rsuite.containerWizard.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://www.rsicms.com/rsuite/ns/conf/container-wizard}metadata-conf" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="acl-id" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
 *       &lt;attribute name="type" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "metadataConf"
})
@XmlRootElement(name = "container-conf")
public class ContainerConf {

    @XmlElement(name = "metadata-conf")
    protected MetadataConf metadataConf;
    @XmlAttribute(name = "acl-id")
    protected String aclId;
    @XmlAttribute(name = "name", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String name;
    @XmlAttribute(name = "type", required = true)
    protected String type;

    /**
     * Gets the value of the metadataConf property.
     * 
     * @return
     *     possible object is
     *     {@link MetadataConf }
     *     
     */
    public MetadataConf getMetadataConf() {
        return metadataConf;
    }

    /**
     * Sets the value of the metadataConf property.
     * 
     * @param value
     *     allowed object is
     *     {@link MetadataConf }
     *     
     */
    public void setMetadataConf(MetadataConf value) {
        this.metadataConf = value;
    }

    /**
     * Gets the value of the aclId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAclId() {
        return aclId;
    }

    /**
     * Sets the value of the aclId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAclId(String value) {
        this.aclId = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

}
