//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.2.11
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2016.06.26 at 08:39:15 AM EDT
//


package com.rsicms.rsuite.containerWizard.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://www.rsicms.com/rsuite/ns/conf/container-wizard}pages"/&gt;
 *         &lt;element ref="{http://www.rsicms.com/rsuite/ns/conf/container-wizard}primary-container"/&gt;
 *         &lt;element ref="{http://www.rsicms.com/rsuite/ns/conf/container-wizard}acls"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
 *       &lt;attribute ref="{http://www.rsuitecms.com/rsuite/ns/metadata}rsuiteId"/&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {"pages", "primaryContainer", "acls"})
@XmlRootElement(name = "container-wizard-conf")
public class ContainerWizardConf {

  @XmlElement(required = true)
  protected Pages pages;
  @XmlElement(name = "primary-container", required = true)
  protected PrimaryContainer primaryContainer;
  @XmlElement(required = true)
  protected Acls acls;
  @XmlAttribute(name = "name", required = true)
  @XmlSchemaType(name = "anySimpleType")
  protected String name;
  @XmlAttribute(name = "rsuiteId", namespace = "http://www.rsuitecms.com/rsuite/ns/metadata")
  protected String rsuiteId;

  /**
   * Gets the value of the pages property.
   * 
   * @return possible object is {@link Pages }
   * 
   */
  public Pages getPages() {
    return pages;
  }

  /**
   * Sets the value of the pages property.
   * 
   * @param value allowed object is {@link Pages }
   * 
   */
  public void setPages(Pages value) {
    this.pages = value;
  }

  /**
   * Gets the value of the primaryContainer property.
   * 
   * @return possible object is {@link PrimaryContainer }
   * 
   */
  public PrimaryContainer getPrimaryContainer() {
    return primaryContainer;
  }

  /**
   * Sets the value of the primaryContainer property.
   * 
   * @param value allowed object is {@link PrimaryContainer }
   * 
   */
  public void setPrimaryContainer(PrimaryContainer value) {
    this.primaryContainer = value;
  }

  /**
   * Gets the value of the acls property.
   * 
   * @return possible object is {@link Acls }
   * 
   */
  public Acls getAcls() {
    return acls;
  }

  /**
   * Sets the value of the acls property.
   * 
   * @param value allowed object is {@link Acls }
   * 
   */
  public void setAcls(Acls value) {
    this.acls = value;
  }

  /**
   * Gets the value of the name property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getName() {
    return name;
  }

  /**
   * Sets the value of the name property.
   * 
   * @param value allowed object is {@link String }
   * 
   */
  public void setName(String value) {
    this.name = value;
  }

  /**
   * Gets the value of the rsuiteId property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getRsuiteId() {
    return rsuiteId;
  }

  /**
   * Sets the value of the rsuiteId property.
   * 
   * @param value allowed object is {@link String }
   * 
   */
  public void setRsuiteId(String value) {
    this.rsuiteId = value;
  }

}
