//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.26 at 11:11:46 PM EDT 
//


package com.rsicms.rsuite.containerWizard.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;choice maxOccurs="unbounded"&gt;
 *         &lt;element ref="{http://www.rsicms.com/rsuite/ns/conf/container-wizard}container-conf"/&gt;
 *         &lt;element ref="{http://www.rsicms.com/rsuite/ns/conf/container-wizard}xml-mo-conf"/&gt;
 *       &lt;/choice&gt;
 *       &lt;attribute name="container-acl-id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="default-contents-acl-id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute ref="{http://www.rsuitecms.com/rsuite/ns/metadata}rsuiteId"/&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "containerConfOrXmlMoConf"
})
@XmlRootElement(name = "contents")
public class Contents {

    @XmlElements({
        @XmlElement(name = "container-conf", type = ContainerConf.class),
        @XmlElement(name = "xml-mo-conf", type = XmlMoConf.class)
    })
    protected List<Object> containerConfOrXmlMoConf;
    @XmlAttribute(name = "container-acl-id", required = true)
    protected String containerAclId;
    @XmlAttribute(name = "default-contents-acl-id", required = true)
    protected String defaultContentsAclId;
    @XmlAttribute(name = "rsuiteId", namespace = "http://www.rsuitecms.com/rsuite/ns/metadata")
    protected String rsuiteId;

    /**
     * Gets the value of the containerConfOrXmlMoConf property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the containerConfOrXmlMoConf property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContainerConfOrXmlMoConf().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ContainerConf }
     * {@link XmlMoConf }
     * 
     * 
     */
    public List<Object> getContainerConfOrXmlMoConf() {
        if (containerConfOrXmlMoConf == null) {
            containerConfOrXmlMoConf = new ArrayList<Object>();
        }
        return this.containerConfOrXmlMoConf;
    }

    /**
     * Gets the value of the containerAclId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContainerAclId() {
        return containerAclId;
    }

    /**
     * Sets the value of the containerAclId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContainerAclId(String value) {
        this.containerAclId = value;
    }

    /**
     * Gets the value of the defaultContentsAclId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDefaultContentsAclId() {
        return defaultContentsAclId;
    }

    /**
     * Sets the value of the defaultContentsAclId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDefaultContentsAclId(String value) {
        this.defaultContentsAclId = value;
    }

    /**
     * Gets the value of the rsuiteId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRsuiteId() {
        return rsuiteId;
    }

    /**
     * Sets the value of the rsuiteId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRsuiteId(String value) {
        this.rsuiteId = value;
    }

}
