//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.26 at 08:39:15 AM EDT 
//


package com.rsicms.rsuite.containerWizard.jaxb;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.rsicms.rsuite.containerWizard.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.rsicms.rsuite.containerWizard.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ContainerWizardConf }
     * 
     */
    public ContainerWizardConf createContainerWizardConf() {
        return new ContainerWizardConf();
    }

    /**
     * Create an instance of {@link Pages }
     * 
     */
    public Pages createPages() {
        return new Pages();
    }

    /**
     * Create an instance of {@link Page }
     * 
     */
    public Page createPage() {
        return new Page();
    }

    /**
     * Create an instance of {@link PrimaryContainer }
     * 
     */
    public PrimaryContainer createPrimaryContainer() {
        return new PrimaryContainer();
    }

    /**
     * Create an instance of {@link MetadataConf }
     * 
     */
    public MetadataConf createMetadataConf() {
        return new MetadataConf();
    }

    /**
     * Create an instance of {@link NameValuePair }
     * 
     */
    public NameValuePair createNameValuePair() {
        return new NameValuePair();
    }

    /**
     * Create an instance of {@link ContainerConf }
     * 
     */
    public ContainerConf createContainerConf() {
        return new ContainerConf();
    }

    /**
     * Create an instance of {@link XmlMoConf }
     * 
     */
    public XmlMoConf createXmlMoConf() {
        return new XmlMoConf();
    }

    /**
     * Create an instance of {@link Acls }
     * 
     */
    public Acls createAcls() {
        return new Acls();
    }

    /**
     * Create an instance of {@link Acl }
     * 
     */
    public Acl createAcl() {
        return new Acl();
    }

    /**
     * Create an instance of {@link Ace }
     * 
     */
    public Ace createAce() {
        return new Ace();
    }

}
