//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.2.11
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2016.06.26 at 08:39:15 AM EDT
//


package com.rsicms.rsuite.containerWizard.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;attribute name="action-id" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="form-id" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="api-name" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="sub-pages" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "page")
public class Page {

  @XmlAttribute(name = "action-id")
  protected String actionId;
  @XmlAttribute(name = "form-id")
  protected String formId;
  @XmlAttribute(name = "api-name")
  protected String apiName;
  @XmlAttribute(name = "sub-pages", required = true)
  protected boolean subPages;

  /**
   * Gets the value of the actionId property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getActionId() {
    return actionId;
  }

  /**
   * Sets the value of the actionId property.
   * 
   * @param value allowed object is {@link String }
   * 
   */
  public void setActionId(String value) {
    this.actionId = value;
  }

  /**
   * Gets the value of the formId property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getFormId() {
    return formId;
  }

  /**
   * Sets the value of the formId property.
   * 
   * @param value allowed object is {@link String }
   * 
   */
  public void setFormId(String value) {
    this.formId = value;
  }

  /**
   * Gets the value of the apiName property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getApiName() {
    return apiName;
  }

  /**
   * Sets the value of the apiName property.
   * 
   * @param value allowed object is {@link String }
   * 
   */
  public void setApiName(String value) {
    this.apiName = value;
  }

  /**
   * Gets the value of the subPages property.
   * 
   */
  public boolean isSubPages() {
    return subPages;
  }

  /**
   * Sets the value of the subPages property.
   * 
   */
  public void setSubPages(boolean value) {
    this.subPages = value;
  }

}
