//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.2.11
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2016.06.26 at 08:39:15 AM EDT
//


package com.rsicms.rsuite.containerWizard.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://www.rsicms.com/rsuite/ns/conf/container-wizard}metadata-conf" minOccurs="0"/&gt;
 *         &lt;choice maxOccurs="unbounded"&gt;
 *           &lt;element ref="{http://www.rsicms.com/rsuite/ns/conf/container-wizard}container-conf"/&gt;
 *           &lt;element ref="{http://www.rsicms.com/rsuite/ns/conf/container-wizard}xml-mo-conf"/&gt;
 *         &lt;/choice&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="type" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="acl-id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="default-acl-id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute ref="{http://www.rsuitecms.com/rsuite/ns/metadata}rsuiteId"/&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {"metadataConf", "containerConfOrXmlMoConf"})
@XmlRootElement(name = "primary-container")
public class PrimaryContainer {

  @XmlElement(name = "metadata-conf")
  protected MetadataConf metadataConf;
  @XmlElements({@XmlElement(name = "container-conf", type = ContainerConf.class), @XmlElement(
      name = "xml-mo-conf", type = XmlMoConf.class)})
  protected List<Object> containerConfOrXmlMoConf;
  @XmlAttribute(name = "type", required = true)
  protected String type;
  @XmlAttribute(name = "acl-id", required = true)
  protected String aclId;
  @XmlAttribute(name = "default-acl-id", required = true)
  protected String defaultAclId;
  @XmlAttribute(name = "rsuiteId", namespace = "http://www.rsuitecms.com/rsuite/ns/metadata")
  protected String rsuiteId;

  /**
   * Gets the value of the metadataConf property.
   * 
   * @return possible object is {@link MetadataConf }
   * 
   */
  public MetadataConf getMetadataConf() {
    return metadataConf;
  }

  /**
   * Sets the value of the metadataConf property.
   * 
   * @param value allowed object is {@link MetadataConf }
   * 
   */
  public void setMetadataConf(MetadataConf value) {
    this.metadataConf = value;
  }

  /**
   * Gets the value of the containerConfOrXmlMoConf property.
   * 
   * <p>
   * This accessor method returns a reference to the live list, not a snapshot. Therefore any
   * modification you make to the returned list will be present inside the JAXB object. This is why
   * there is not a <CODE>set</CODE> method for the containerConfOrXmlMoConf property.
   * 
   * <p>
   * For example, to add a new item, do as follows:
   * 
   * <pre>
   * getContainerConfOrXmlMoConf().add(newItem);
   * </pre>
   * 
   * 
   * <p>
   * Objects of the following type(s) are allowed in the list {@link ContainerConf }
   * {@link XmlMoConf }
   * 
   * 
   */
  public List<Object> getContainerConfOrXmlMoConf() {
    if (containerConfOrXmlMoConf == null) {
      containerConfOrXmlMoConf = new ArrayList<Object>();
    }
    return this.containerConfOrXmlMoConf;
  }

  /**
   * Gets the value of the type property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getType() {
    return type;
  }

  /**
   * Sets the value of the type property.
   * 
   * @param value allowed object is {@link String }
   * 
   */
  public void setType(String value) {
    this.type = value;
  }

  /**
   * Gets the value of the aclId property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getAclId() {
    return aclId;
  }

  /**
   * Sets the value of the aclId property.
   * 
   * @param value allowed object is {@link String }
   * 
   */
  public void setAclId(String value) {
    this.aclId = value;
  }

  /**
   * Gets the value of the defaultAclId property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getDefaultAclId() {
    return defaultAclId;
  }

  /**
   * Sets the value of the defaultAclId property.
   * 
   * @param value allowed object is {@link String }
   * 
   */
  public void setDefaultAclId(String value) {
    this.defaultAclId = value;
  }

  /**
   * Gets the value of the rsuiteId property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getRsuiteId() {
    return rsuiteId;
  }

  /**
   * Sets the value of the rsuiteId property.
   * 
   * @param value allowed object is {@link String }
   * 
   */
  public void setRsuiteId(String value) {
    this.rsuiteId = value;
  }

}
